### PR TITLE
Config updates

### PR DESCRIPTION
**Pull request by N0NB**
Tom,

This mostly completes the updates to the build system.  I do have one suggestion and that is to replace the three email addresses in the call to the AC_INIT macro with the address of the mailing list.  It's not my intention to slight anyone by doing so and I certainly did not wish to make the list even longer by adding my own.  It is my thought shortening the list makes it easier for users to reach the project and gives a consistent reporting address regardless of who is involved as the project goes forward.

Second, on my system the check for the floor and sqrt functions fails in the AC_CHECK_FUNCS macro.  Per their respective man pages they are a part of the math library and not the C library, although that may not be true on all systems.  It's not a show stopper by any means and I'm inclined to leave them well enough alone until we receive a report that a library in addition to the subsequently detected math library is required.

### CODE REVIEW

**Comment by dl1jbe** [comment]
Hi Nate,

thanks again. I will have a  look in next time. I hope it will be done
before christmas... 

Do you see my reported issue https://github.com/Tlf/tlf/issues/57 about
some problems with the ncurses header solution?

Tom.

Am Sat, 19 Dec 2015 07:20:23 -0800
schrieb Nate Bargmann <notifications@github.com>:

> Tom,
> 
> This mostly completes the updates to the build system.  I do have one
> suggestion and that is to replace the three email addresses in the
> call to the AC_INIT macro with the address of the mailing list.  It's
> not my intention to slight anyone by doing so and I certainly did not
> wish to make the list even longer by adding my own.  It is my thought
> shortening the list makes it easier for users to reach the project
> and gives a consistent reporting address regardless of who is
> involved as the project goes forward.
> 
> Second, on my system the check for the floor and sqrt functions fails
> in the AC_CHECK_FUNCS macro.  Per their respective man pages they are
> a part of the math library and not the C library, although that may
> not be true on all systems.  It's not a show stopper by any means and
> I'm inclined to leave them well enough alone until we receive a
> report that a library in addition to the subsequently detected math
> library is required. You can view, comment on, or merge this pull
> request online at:
> 
>   https://github.com/Tlf/tlf/pull/58
> 
> -- Commit Summary --
> 
>   * Use glib macro to detect glib
>   * Update to AX_PTHREAD macro
>   * Update Hamlib stanza in configure.ac
>   * Update Fldigi XML RPC stanza in configure.ac
>   * Use AX_CFLAGS_WARN_ALL to determine compiler warnings
>   * Define PACKAGE_DATA_DIR in src/Makefile.am
>   * Set LIBM_LIB to preserve the LIBS variable
> 
> -- File Changes --
> 
>     D acinclude.m4 (227)
>     M configure.ac (162)
>     A macros/ax_append_flag.m4 (71)
>     A macros/ax_cflags_warn_all.m4 (122)
>     A macros/ax_pthread.m4 (332)
>     A macros/ax_require_defined.m4 (37)
>     M src/Makefile.am (7)
>     M src/addmult.c (4)
>     M src/readctydata.c (4)
>     M src/rules.c (4)
>     M src/searchlog.c (4)
>     M src/show_help.c (4)
>     M src/writecabrillo.c (4)
> 
> -- Patch Links --
> 
> https://github.com/Tlf/tlf/pull/58.patch
> https://github.com/Tlf/tlf/pull/58.diff
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tlf/tlf/pull/58



-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by N0NB** [comment]
Commentary added to #57.

**Comment by dl1jbe** [comment]
I pulled in only the first two patches from your pull request for now. They work fine.
If I apply the following patch my hamlib installation is no longer found (teh lib is in /usr/lib64/hamlib here).
Can you please have a look at it? Thanks

**Comment by N0NB** [comment]
* On 2015 23 Dec 06:03 -0600, Thomas Beierlein wrote:
> I pulled in only the first two patches from your pull request for
> now. They work fine.  If I apply the following patch my hamlib
> installation is no longer found (teh lib is in /usr/lib64/hamlib
> here).  Can you please have a look at it? Thanks

Hi Tom.

What does your hamlib.pc file look like?  Can you pass along the
config.log as well?

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by N0NB** [comment]
Ping Tom!

Off on holiday?

**Comment by dl1jbe** [comment]
Pong!

You guessed nearly right. Please see private mail with the attached files.

**Comment by N0NB** [comment]
Tom, please try this patch.  I am setting the user variables temporarily to the paths found by pkg-config.

**Comment by dl1jbe** [comment]
Am Wed, 30 Dec 2015 15:35:40 -0800
schrieb Nate Bargmann <notifications@github.com>:

> Tom, please try this patch.  I am setting the user variables
> temporarily to the paths found by pkg-config.

Looks good so far. I will do some more tests and than pull it in.

73, Tom
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tlf/tlf/pull/58#issuecomment-168095562


-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by N0NB** [comment]
Thanks, Tom.

HNY!

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Pull request merged**
