### PR TITLE
Use actual QSO mode for mode-based scoring

### LINKED ISSUE #341: Re-scoring does not consider QSO mode
Rescoring a log with mixed mode QSOs and using mode scoring (CWPOINTS/SSBPOINTS) leads to a wrong result. All QSOs are scored using the actually selected mode (normally CW).
For an example see #273.

### PR DESCRIPTION
**Pull request by zcsahok**
Fixes #341

On mid term we shall replace `trxmode` with `current_qso.mode` similarly to #336.

### CODE REVIEW

**Comment by N0NB** [comment]
I made a quick glance at your commit and it appears reasonable.  I've not pulled and tested it yet.

**Review by N0NB — APPROVED** [review]
At first glance these changes look reasonable to me.  I have pulled and built it and the rescore on startup did not change the point values in the log.

**Comment by N0NB** [comment]
I see that the QSO point score matches that of my Perl script although the multipliers are way too many but that is another bug.

**Comment by zcsahok** [comment]
Thanks for checking!

**Pull request merged**
