### PR TITLE
ARRL 160m rules, look for MULT_LIST in installation directory, fix typos in man page

### PR DESCRIPTION
**Pull request by N0NB**
This request brings my master up to date with upstream master.

I have included the rules file for the ARRL 160m USA side that is working for me.

I found that Tlf only checked the working directory for the file specified in MULT_LIST.  This patch also checks the installation directory--/usr/local/share/tl--etc.

Fixed a few typos in the Tlf man page.

### CODE REVIEW

**Comment by dl1jbe** [comment]
Many thanks Nate. Good work - the MULT_LIST handling fixes one of the items from my todo list....

In meantime I cherry-picked most of your work into the master branch. I left out the formatting of addmult.c for the moment. I think it needs some discussion and improvement:

- I appreciate the changes in the comments (positioning and wording)
- I do not want to add the whole lot of whitespace changes at the line starts (tlf's code uses tabs for 8 spaces and only use spaces if we have an indent of 4, 12 or somthing like that.
- The initialisation of the 'inxes' field (line 42) should stay indented. It is an continuation of the line before.
- The if-statement in line 119 should stay on two lines. Otherwise we got a line length > 80. (I know there are more such places in the code, but I do not like them either...).
- Having empty lines at start and end of an { } block makes code more readable, but I am open for suggestions.

Maybe we should add an README.developer file and formulate a common coding style for tlf.

**Comment by N0NB** [comment]
* On 2015 06 Dec 06:23 -0600, Thomas Beierlein wrote:
> Many thanks Nate. Good work - the MULT_LIST handling fixes one of the
> items from my todo list....

Glad to have checked one of those off, heh!

> In meantime I cherry-picked most of your work into the master
> branch. I left out the formatting of addmult.c for the moment. I think
> it needs some discussion and improvement:
> 
> - I appreciate the changes in the comments (positioning and wording)

I tend to like comments that describe a block to be placed before it.
I'm not a fan of comments on the same line as '{'.  A short comment to
describe a variable can be on the same line, however.

> - I do not want to add the whole lot of whitespace changes at the line
> starts (tlf's code uses tabs for 8 spaces and only use spaces if we
> have an indent of 4, 12 or somthing like that.

I was wondering if you'd notice.  ;-)

8 space-width tabs is fine and generally what I prefer in C (not a fan
of GNU style).  Not sure what I was thinking that day committing 4
spaces instead.  I was getting a bit lost in the flow so I ran it
through astyle with tabs for indent and Geany misbehaved so I set it to
four spaces (more below).

> - The initialisation of the 'inxes' field (line 42) should stay
> indented. It is an continuation of the line before.

Perhaps it could be broken with '\' so the first part is with the
assignment and the rest on the next line(s)?

> - The if-statement in line 119 should stay on two lines. Otherwise we
> got a line length > 80. (I know there are more such places in the
> code, but I do not like them either...).

I can appreciate an 80 character limit.  Perhaps I should adopt the '\'
syntax above more often.  I generally code on a wider GUI screen but
there are times when I do something via SSH and I'm often in the 80
character keyhole.  Then I'm either dealing with editor line wrapping or
scrolling right and left.

> - Having empty lines at start and end of an { } block makes code more
> readable, but I am open for suggestions.

If that is preferred, I am fine with it.  I can especially appreciate it
where an if or for statement condition wraps onto multiple lines to
provide some visual separation from the condition and the block.

> Maybe we should add an README.developer file and formulate a common
> coding style for tlf.

I ran it through a program called astyle that is very configurable.  In
this case I set it to four spaces, for whatever reason that was in my
head that day.  I know there is also the GNU indent program and Emacs
will format code to various styles.  Perhaps the group can adopt a
recipe for one of those programs as the recommended style for Tlf.  I do
need to train my editor (Geany) better for dealing with tabs.  I'm also
fairly adept at using Emacs as well.  For some tasks I prefer the UI of
Geany.

I'll pull your present copy of that file into my tree so we're back in
sync.

I appreciate your feedback, Tom.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by airween** [comment]
Just a small note to (an accidental) indent rule: I think it doesn't matter, which indent style is the favourite :). There is the `indent' program (and several others), which can be format the result, before the developer commit it. (May be the git know it too, I don't know that...). It would be the best, that Thomas would define a rule for ident (or any other indent tool).

73, Ervin

**Comment by dl1jbe** [comment]
Am Sun, 06 Dec 2015 07:45:30 -0800
schrieb Nate Bargmann <notifications@github.com>:

> * On 2015 06 Dec 06:23 -0600, Thomas Beierlein wrote:
snip 
...
> > In meantime I cherry-picked most of your work into the master
> > branch. I left out the formatting of addmult.c for the moment. I
> > think it needs some discussion and improvement:
> > 
> > - I appreciate the changes in the comments (positioning and wording)
> 
> I tend to like comments that describe a block to be placed before it.
> I'm not a fan of comments on the same line as '{'.  A short comment to
> describe a variable can be on the same line, however.
> 
That is my preferred style also. But there is a lot of old code and
also old comments in tlf. I just do not like to just run around and
change at all ends without need. When time comes to clean up or fix some
code the comments will be cleaned up too. Downside is we have a mix of
old and new comment styles in the code base.

> > - I do not want to add the whole lot of whitespace changes at the
> > line starts (tlf's code uses tabs for 8 spaces and only use spaces
> > if we have an indent of 4, 12 or somthing like that.
> 
> I was wondering if you'd notice.  ;-)
> 
That was easy ;-).

> 8 space-width tabs is fine and generally what I prefer in C (not a fan
> of GNU style).  Not sure what I was thinking that day committing 4
> spaces instead.  I was getting a bit lost in the flow so I ran it
> through astyle with tabs for indent and Geany misbehaved so I set it
> to four spaces (more below).
> 
To be more precise. I favor a indentation of 4 for each level but use
tabs in the file for a multiple of 8 spaces. More below at the 'editor'
section...

> > - The initialisation of the 'inxes' field (line 42) should stay
> > indented. It is an continuation of the line before.
> 
> Perhaps it could be broken with '\' so the first part is with the
> assignment and the rest on the next line(s)?
> 
Agreed and applied in meantime.

> > - The if-statement in line 119 should stay on two lines. Otherwise
> > we got a line length > 80. (I know there are more such places in the
> > code, but I do not like them either...).
> 
> I can appreciate an 80 character limit.  Perhaps I should adopt the
> '\' syntax above more often.  I generally code on a wider GUI screen
> but there are times when I do something via SSH and I'm often in the
> 80 character keyhole.  Then I'm either dealing with editor line
> wrapping or scrolling right and left.
 
Yes it is easy to forget about it in an GUI environment. There are some
editors still that put a reminder line on screen. 

> > - Having empty lines at start and end of an { } block makes code
> > more readable, but I am open for suggestions.
> 
> If that is preferred, I am fine with it.  I can especially appreciate
> it where an if or for statement condition wraps onto multiple lines to
> provide some visual separation from the condition and the block.
> 
Especially the empty line above can help to visual distinct between the
multiline conditional and the start of the code. The empty line below
is seldom of any use.

I like empty lines as breaks in the flow of code. It is the same as
paragraphs in text - some ideas ends and a new bunch of ideas starts.


> > Maybe we should add an README.developer file and formulate a common
> > coding style for tlf.
> 
> I ran it through a program called astyle that is very configurable.
> In this case I set it to four spaces, for whatever reason that was in
> my head that day.  I know there is also the GNU indent program and
> Emacs will format code to various styles.  Perhaps the group can
> adopt a recipe for one of those programs as the recommended style for
> Tlf.  I do need to train my editor (Geany) better for dealing with
> tabs.  I'm also fairly adept at using Emacs as well.  For some tasks
> I prefer the UI of Geany.
> 
There is the quite nice 'universalindentgui' interface. It makes it a
little bit easier to manage the command line switches for astyle,
indent or other formatters.

I by myself use VI for editing and it is not difficult to set it up. Vi
allows a 'smartindnet' mode where it use a 'softtab' setting for indent
but replaces it with hard tabs if possible. So I use softtabs = 4 for
indentation but tabstop = 8 for the tabs. The rest is just plain vi
magic ;-). 

(In meantime I rediscovered the 'retab!' command in vi which replaces
your spaces by tabs back again.)

If you find something similar in your editor please let us know. We
should add these tips to the considered README.developer.


Thanks for the helpful discussion,

73, de Tom.



-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by dl1jbe** [comment]
Am Sun, 06 Dec 2015 08:02:23 -0800
schrieb Ervin Hegedus <notifications@github.com>:

> Just a small note to (an accidental) indent rule: I think it doesn't
> matter, which indent style is the favourite :). There is the `indent'
> program (and several others), which can be format the result, before
> the developer commit it. 

Right, Ervin. I just would like to avoid committing changes to the repo
which only switches the indent style back and forth.

> (May be the git know it too, I don't know
> that...). It would be the best, that Thomas would define a rule for
> ident (or any other indent tool).
>
As I wrote in the other comment I will provide some README.developer
in next days and hope for comments.

73, de Tom


-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by N0NB** [comment]
* On 2015 06 Dec 10:41 -0600, Thomas Beierlein wrote:
> That is my preferred style also. But there is a lot of old code and
> also old comments in tlf. I just do not like to just run around and
> change at all ends without need. When time comes to clean up or fix some
> code the comments will be cleaned up too. Downside is we have a mix of
> old and new comment styles in the code base.

That is why I only touched addmult.c in such a manner as I was doing
more than just fixing a typo or some such.  I'm not going to go around
reformatting everything.  Before I do that, I'd best turn my attention
to Hamlib first!  :-O

> To be more precise. I favor a indentation of 4 for each level but use
> tabs in the file for a multiple of 8 spaces. More below at the 'editor'
> section...

So two tabs to get to the ninth column?

I know, there are plenty of religious wars to be found all over the 'Net
on indentation, so I will refrain from starting one here.  I will do my
best to maintain the same style regardless of my editor.  That said,
Geany does have an interesting configuration where it will adopt the
format of the file, if possible.

I know that Vim, and possibly Emacs, can imbed tab settings in a source
file comment.  The authors of Geany could consider applying those.  I'm
getting way off topic here!

> Yes it is easy to forget about it in an GUI environment. There are some
> editors still that put a reminder line on screen.

Geany actually has such a marker--a bright cyan line in my case--on the
screen, so no excuse from me.  ;-)

> Especially the empty line above can help to visual distinct between the
> multiline conditional and the start of the code. The empty line below
> is seldom of any use.
> 
> I like empty lines as breaks in the flow of code. It is the same as
> paragraphs in text - some ideas ends and a new bunch of ideas starts.

I do prefer to separate conditionals from prior code by at least one
blank line.  My only personal exception is when a conditional is the
first line in an indented block  as in:

      for (....) {
          if (...) {
             .
             .
             .
          }
      }

> There is the quite nice 'universalindentgui' interface. It makes it a
> little bit easier to manage the command line switches for astyle,
> indent or other formatters.

I use an .astylerc in my home directory and modify it once in a great
while.  I'll put a copy on my gist where anyone can take a look.

> I by myself use VI for editing and it is not difficult to set it up. Vi
> allows a 'smartindnet' mode where it use a 'softtab' setting for indent
> but replaces it with hard tabs if possible. So I use softtabs = 4 for
> indentation but tabstop = 8 for the tabs. The rest is just plain vi
> magic ;-). 
> 
> (In meantime I rediscovered the 'retab!' command in vi which replaces
> your spaces by tabs back again.)

It took me long enough to warm up to Tlf, is there hope for me and Vim?
I know there is a Vim GTK+ GUI, perhaps I need to revisit it.  The only
problem is that I already know so many CUA keystrokes from years back
that Vim and Emacs, even with their GUIs still seem foreign to me.  It
is amazing what the human mind can remember!

> If you find something similar in your editor please let us know. We
> should add these tips to the considered README.developer.

In the README.developer file I mentioned the Linux kernel style guide as
a starting point and then went from there.  A lot the Linux kernel style
is in use already so just add your points of preference to the file for
Tlf and we're good to go!

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by dl1jbe** [comment]
Am Sun, 06 Dec 2015 09:12:20 -0800
schrieb Nate Bargmann <notifications@github.com>:

> * On 2015 06 Dec 10:41 -0600, Thomas Beierlein wrote:
> > That is my preferred style also. But there is a lot of old code and
> > also old comments in tlf. I just do not like to just run around and
> > change at all ends without need. When time comes to clean up or fix
> > some code the comments will be cleaned up too. Downside is we have
> > a mix of old and new comment styles in the code base.
> 
> That is why I only touched addmult.c in such a manner as I was doing
> more than just fixing a typo or some such.  I'm not going to go around
> reformatting everything.  Before I do that, I'd best turn my attention
> to Hamlib first!  :-O
> 
Yes, I saw it. I think hamlib maybe even a bigger problem regarding the
lot of different programmers which provided code for it (i fear there
are also some old lines from my side ;-) ). 

> > To be more precise. I favor a indentation of 4 for each level but
> > use tabs in the file for a multiple of 8 spaces. More below at the
> > 'editor' section...
> 
> So two tabs to get to the ninth column?
> 
Pressing TAB two times - yes. In the file - only one TAB character.
Pressing three times - one TAB character and 4 spaces in the file.

The iron rule should be: a TAB character in a file is EVER equivalent
to 8 spaces. (Otherwise we will see very nasty formatted code if
some editor defines its tab-size to 2 or 4).

> I know, there are plenty of religious wars to be found all over the
> 'Net on indentation, so I will refrain from starting one here.  I
> will do my best to maintain the same style regardless of my editor.
> That said, Geany does have an interesting configuration where it will
> adopt the format of the file, if possible.
> 
I think a war about indentation between our styles would be not so big.
We are working quite similar.

Geanies feature sounds interesting. Maybe I find time to have a lokk
into it.

> I know that Vim, and possibly Emacs, can imbed tab settings in a
> source file comment.  The authors of Geany could consider applying
> those.  I'm getting way off topic here!
> 
Yeah, but that may be not so good. I try to use tabs only for the
indentation. 

> > Yes it is easy to forget about it in an GUI environment. There are
> > some editors still that put a reminder line on screen.
> 
> Geany actually has such a marker--a bright cyan line in my case--on
> the screen, so no excuse from me.  ;-)
> 
My comment was not to make you feel guilty ;-).

> > Especially the empty line above can help to visual distinct between
> > the multiline conditional and the start of the code. The empty line
> > below is seldom of any use.
> > 
> > I like empty lines as breaks in the flow of code. It is the same as
> > paragraphs in text - some ideas ends and a new bunch of ideas
> > starts.
> 
> I do prefer to separate conditionals from prior code by at least one
> blank line.  My only personal exception is when a conditional is the
> first line in an indented block  as in:
> 
>       for (....) {
>           if (...) {
>              .
>              .
>              .
>           }
>       }
> 
Sounds good. Let us stay to that for new code.

> > There is the quite nice 'universalindentgui' interface. It makes it
> > a little bit easier to manage the command line switches for astyle,
> > indent or other formatters.
> 
> I use an .astylerc in my home directory and modify it once in a great
> while.  I'll put a copy on my gist where anyone can take a look.

Very well. We can add it as recommendation for contributors.

> 
> > I by myself use VI for editing and it is not difficult to set it
> > up. Vi allows a 'smartindnet' mode where it use a 'softtab' setting
> > for indent but replaces it with hard tabs if possible. So I use
> > softtabs = 4 for indentation but tabstop = 8 for the tabs. The rest
> > is just plain vi magic ;-). 
> > 
> > (In meantime I rediscovered the 'retab!' command in vi which
> > replaces your spaces by tabs back again.)
> 
> It took me long enough to warm up to Tlf, is there hope for me and
> Vim? I know there is a Vim GTK+ GUI, perhaps I need to revisit it.
> The only problem is that I already know so many CUA keystrokes from
> years back that Vim and Emacs, even with their GUIs still seem
> foreign to me.  It is amazing what the human mind can remember!
> 
Nate, just stay with the editor you like and mastered already. I am
using vi for 25 years now and I still discover new features often. Use
whatever makes you productive. 

> > If you find something similar in your editor please let us know. We
> > should add these tips to the considered README.developer.
> 
> In the README.developer file I mentioned the Linux kernel style guide
> as a starting point and then went from there.  A lot the Linux kernel
> style is in use already so just add your points of preference to the
> file for Tlf and we're good to go!
> 
Ok, so I will have a look and then shamelessly steal whatever is useful.

73 for today,

	Tom



-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by dl1jbe** [comment]
Seems we got all merged in. So I close the pull request. If needed please reopen.

**Pull request closed without merging**
