### PR TITLE
Apply astyle

### PR DESCRIPTION
**Pull request by zcsahok**
Follow-up from #398 - consistently applying astyle to all source files. (src/*.[ch])

Some specially formatted comments are protected using INDENT-OFF/ON.

Trailing comments in main.c moved before the definition they to.

### CODE REVIEW

**Comment by zcsahok** [comment]
The following checksum stays invariant after astyle:
```
$ cat src/*.[ch] | tr -d ' \t\n' | md5sum
4b07abb970a4164588fabb9723365bf2  -
```
(MD5 of all files with whitespace and newlines removed)

**Review by airween — APPROVED** [review]

**Comment by airween** [comment]
Thanks Zoli, nice work.

**Comment by airween** [comment]
I was wondering if we should force the use of astyle, eg. put a small script into the workflow what format the committed code and diff it with the original.

**Comment by zcsahok** [comment]
A check step could be surely added to the actions. Thanks for the idea.

**Comment by zcsahok** [comment]
The check fails if there are files to be formatted. The output provides the list of affected files.
image

**Comment by airween** [comment]
LGTM, thanks!

**Pull request merged**
