### PR TITLE
Fix/typos

### PR DESCRIPTION
**Pull request by dforsi**
This PR fixes some small errors in the documentation and in comments.

### CODE REVIEW

**Comment by zcsahok** [comment]
Thanks.
There is also at least one in `share/logcfg.dat`
```
# or for dots+calss
```

**Comment by dforsi** [comment]
There were two more words in `share/logcfg.dat`.

**Comment by dl1jbe** [comment]
Last correction should be 'calls' not 'class' ;-).

**Comment by dforsi** [comment]
Ops :)
Now I squashed the last commit about `share/logcfg.dat` in the first commit.

**Comment by dl1jbe** [comment]
So, seems no more hints at the moment. Merging it in.
Thanks for the PR.

**Pull request merged**
