### PR TITLE
Test MWC rules

### PR DESCRIPTION
**Pull request by zcsahok**
Added test for MWC rules.

Updated `run_tlf.py` to clean up `__pycache__` directory.

### CODE REVIEW

**Comment by zcsahok** [comment]
Oops, there is no plugin for Ubuntu 20, have to somehow disable the test.

**Comment by dl1jbe** [comment]
Is there a missing -enable-python-plugin in the ci-built-ubuntu-20.yml?

**Comment by zcsahok** [comment]
Ubuntu 20 has Python 3.8 version, plugin code needs 3.10. The build has been added to detect any issues with legacy systems, but is compiles without plugin support.

**Comment by zcsahok** [comment]
Now tests with a `*.py` in rules dir are skipped no plugins are supported.
The only thing is that one does not see from the action output which rules were actually tested.

**Comment by dl1jbe** [comment]
As I read configure.ac it looks like 3.9 is the minimum required version for the plugin, or do I miss something?
It is a little bit weird that we require different minimum python versions for running the rules_test and for checking contest which use the plugin.

The automatic skip of *.py tests looks good. The tested rules should be readable from test/run_rules.log.

**Comment by zcsahok** [comment]
Maybe it was 3.8 having some issues, I don't remember now  exactly. So, at least with 3.9 all works fine (probably I was mixing this up with 3.10, sri).
But for the testing script itself 3.8 is enough. The separate check has been added explicitly to support Ubuntu 20 build.

**Comment by dl1jbe** [comment]
As the python plugin is now merged into master we should adapt our README.md to reflect the new configure switch and the Python and pexpect requirements. Shall I do?

**Comment by zcsahok** [comment]
Yes, please.

**Pull request merged**
