### PR TITLE
update "repeat number" string

### PR DESCRIPTION
**Pull request by dh5fs**
its better to send "5NN" as prefix before repeating the number than NR, some people react better to that under low S/N conds

### CODE REVIEW

**Comment by dl1jbe** [comment]
Good Idea Fred. I have just one small comment: I know most of us
use simple 5nn for rst but as tlf allows you to change tlf-sent for
the qso it seems better to be consistent and repeat what you gave in
the first report.

**Comment by dh5fs** [comment]
Thats true. I use mostly shorted numbers.

**Comment by dl1jbe** [comment]
Ok. So it should use the actual rst and also honor the SHORT_SERIAL setting. 
I added it to the todo list.

**Comment by dl1jbe** [comment]
Sorry for being so late. Lot of QRL here. Please test and report back if needed.

**Comment by dh5fs** [comment]
Works!! TU!

**Pull request merged**
