### PR TITLE
sendbuf.c: reworked ExpandMacro

### PR DESCRIPTION
**Pull request by zcsahok**
Hi,

Trying to get a better readable code and also get rid of buffer overruns.

73!

### CODE REVIEW

**Comment by dl1jbe** [comment]
Hi Zoltan,
thanks for the patch. To split out a replace() function looks like a very good idea.

I tried to understand your work and got two questions. Maybe you can give some background to me:
- You do some replacements unconditionally (% and [) and sometimes (@ and #) you check before if the string does contain the character to be replaced. What is the idea behind that difference?
- I am not quite sure if we always get 0-terminated strings out of the expansion. The strncpy function has the nasty side effect that it does not guarantee the correct string termination if the buffer gets filled. Can you please check again? (As an idea - there is a safe g_strlcpy function in glib. Maybe we shoudl use it here).
73, Tom DL1JBE

**Comment by zcsahok** [comment]
Hi Tom,

Thanks for your feedback.
The patch has no (intended) functional changes. The handling of @ and # is special as it involves side effects: for @ auto-sending state must be updated and for # the serial number shall be sent over the net if needed. So in these cases a check before starting with replacement is necessary. It was also quite hard to understand for me what was going on there...

I'm aware of strcnpy's working, so to be really sure I'll double check the replacement function and also consider using g_strlcpy.

73,
Zoli
ha5cqz

**Comment by dl1jbe** [comment]
Thanks for the clarification, Zoli.
> 
> I'm aware of strcnpy's working, so to be really sure I'll double check
> the replacement function and also consider using g_strlcpy.
> 
Please give me an information when you are ready. Be aware that I will be away until tuesday.

73, de Tom DL1JBE

**Comment by zcsahok** [comment]
I'll let you when I'm finished. Have a nice WE.

73,
Zoli

**Comment by zcsahok** [comment]
Hi Tom,
Fixed replace_n and improved it to do all the work really in-place.
I have a bunch of test cases checked in in src/test. Its Makefile is not integrated to the main autoconfig mechanism, though.

73,
Zoli

**Comment by dl1jbe** [comment]
Very well Zoltan.
I applied and pushed your changes. 
The tests got integrated into my own internal test suite (just started some month ago, not published yet). I normally use cmocka test suite, but the minunit looks nice also.

Thanks, Tom DL1JBE

**Comment by dl1jbe** [comment]
Let us close the old pull request as the new one (#69) reflects the last changes best.

**Pull request closed without merging**
