### PR TITLE
Fix getline usage

### PR DESCRIPTION
**Pull request by darvark**
Fixes according to issue https://github.com/Tlf/tlf/issues/414.

Still can't find solution for failing test_rules error.

### CODE REVIEW

**Comment by zcsahok** [comment]
The tests seem to be all OK.

**Comment by dl1jbe** [comment]
Looks much better and fixes most problems.

Just one question left: What do you want to check with the lines like

```
if (s_inputbuffer_len > 0) {
```
and similar. Do you want to make sure there is an allocated buffer? That should be guaranteed by readline() returning without an error.

**Comment by darvark** [comment]
Yes I want to be sure that something was read. getline will return -1 only in case of error i other case returns number of characters read. So it can return in theory 0, and function will have to work on zero length buffer? In theory I can remove that check, but not sure if it's sully desired and safe

**Comment by dl1jbe** [comment]
I see. But than you should test the value returned by getline() instead. That would be

'''
while ((read = getline(&s_inputbuffer, &s_inputbuffer_len, cfp)) != -1) {
  if (read > 0) {
   ....
  }
}
'''

If I read the man page right the inputbuffer will be expanded as needed but not shrink-ed if it is to large, so its size from 's_inputbuffer_len' may not represent the line length.

**Comment by darvark** [comment]
Right, Ok, switching condition. Meanwhile one question (not related to that PR). Is there any documentation about usage python plugins? We can enable support or python plugins, bu I didn't found anything about usage or how to write them

**Comment by dl1jbe** [comment]
> Meanwhile one question (not related to that PR). Is there any documentation about usage python plugins? We can enable support or python plugins, bu I didn't found anything about usage or how to write them

Please see TLFs man page section `PYTHON PLUGIN'.

As the plugin was made by Zoli, he can give more informations if needed.

**Comment by dl1jbe** [comment]
Your code looks good now. There are some places were a check for empty lines is already in place. But we will sort that out later.

Thanks for the work on it. Will merge it in now.

**Pull request merged**
