### PR TITLE
Add rules for North American QSO party

### PR DESCRIPTION
**Pull request by VictorDenisov**

### CODE REVIEW

**Comment by dl1jbe** [comment]
Hi Victor, thx for the PR. 

handling may take a little time as I catched the flu (maybe I should say it catched me...).

Some quick suggestions:
* Please add date and author as in CQP (makes it easier to keep the rules up to date)
* It would be good if you can prepare a minimal log file which demonstrates the rules (given/not given multipliers and points, handling of multiband contacts). We just introduce a test mechanism to catch if code changes introduce errors in existing contest rules (see PR #379).

**Comment by zcsahok** [comment]
Vic, could you maybe also add KSQP rules from #273? I assume they share the same logic.

**Comment by dl1jbe** [comment]
May I remind to my ask for a minimal sample log file demonstrating the rules. Otherwise I will merge it in as is.

**Comment by VictorDenisov** [comment]
Got a bit distracted. I'll do it.

**Comment by VictorDenisov** [comment]
@dl1jbe Could you please take a look at the tests I added. I looked at cqww as an example, but it seems I'm missing something. If it looks good I'll add rules for ksqp as @zcsahok requested.

**Comment by VictorDenisov** [comment]
I see that there is an automated build run, but it's not immediately obvious to me what I broke.

**Comment by zcsahok** [comment]
To see whats wrong with your rule test
* configure and build tlf as usual (with plugin support)
* switch to test/rules/naqp
* execute `../../../src/tlf -nrv`

If all is OK then no change in the log shall occur.

For naqp a log change is detected and here are the first few lines of the updated and the original log. 

```
==> 20230331_055002_naqp.log <==
 20CW  14-Jan-23 18:08 0001  W7SW           ---  ---  ROD AZ        AZ       1  14045.0
 20CW  14-Jan-23 18:09 0002  WA7CPA         ---  ---  ALAN WA       WA       1  14040.3
 20CW  14-Jan-23 18:15 0003  W0GAS          ---  ---  GREG CO       CO       1  14035.8
 20CW  14-Jan-23 18:35 0004  W0IZ           ---  ---  IZ CO                  1  14037.0
 20CW  14-Jan-23 18:45 0005  K0EJ           ---  ---  MARK TN       TN       1  14027.7

==> naqp.log <==
 20CW  14-Jan-23 18:08 0001  W7SW           ---  ---  ROD AZ                 0  14045.0
 20CW  14-Jan-23 18:09 0002  WA7CPA         ---  ---  ALAN WA                0  14040.3
 20CW  14-Jan-23 18:15 0003  W0GAS          ---  ---  GREG CO                0  14035.8
 20CW  14-Jan-23 18:35 0004  W0IZ           ---  ---  IZ CO                  0  14037.0
 20CW  14-Jan-23 18:45 0005  K0EJ           ---  ---  MARK TN                0  14027.7
```

It seems like the checked-in version was created with the plugin not active (or different rules) as the updated one has the correct mult+score info.

**Comment by VictorDenisov** [comment]
I turned out I didn't link the .py file in the rules directory.

**Comment by VictorDenisov** [comment]
I'll also need to add Kansas QP rules.

**Comment by VictorDenisov** [comment]
@zcsahok I started looking into Kansas rules and it looks like they are not as straight forward as it looked on the surface. I'll add them but it probably makes sense to publish them in a separate PR.

**Comment by zcsahok** [comment]
OK, thanks for checking KS rules. Let's make them separately.

**Comment by dl1jbe** [comment]
> Got a bit distracted. I'll do it.

Seems you are not the only one with that problem :-(. Sorry.

Just tested your PR. Looks good and works without problems. Thanks.

**Pull request merged**
