### PR TITLE
darc_mults

### PR DESCRIPTION
**Pull request by dh5fs**
Multiplier file for DARC contests (Oct/14)

### CODE REVIEW

**Comment by dl1jbe** [comment]
Thanks, merged in.

Do you have some special cotnests in mind?

**Comment by dh5fs** [comment]
Useable for all contests organized by the german radio club (DARC) which use DOKs a multiplier and/or exchange like WAG/XMAS/DARC 10m contest etc.

**Comment by dh5fs** [comment]
ps. to be used with INITIAL_EXCHANGE Format: INITIAL_EXCHANGE=darc_mults

**Comment by dl1jbe** [comment]
Ah, thanks. I did not see the usage via INITIAL_EXCHANGE=....

**Pull request merged**
