### PR TITLE
Updated FSF snail mail address and license text to the current version

### PR DESCRIPTION
**Pull request by yarda**
Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

### CODE REVIEW

**Review by airween — APPROVED** [review]
LGTM

**Comment by zcsahok** [comment]
@yarda could you add a pointer to the current license text for the record?

**Comment by yarda** [comment]
It's downloaded from the gnu.org:
https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

**Comment by yarda** [comment]
> It's downloaded from the gnu.org:
> https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

Do you want the commit message to be updated?

**Comment by yarda** [comment]
FTR found during the Fedora review - we are trying to get the package to the Fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1979096

**Comment by zcsahok** [comment]
thanks for the info, it's fine with me.

**Review by zcsahok — COMMENTED** [review]
ok

**Pull request merged**
