### PR TITLE
Use keypad

### PR DESCRIPTION
**Pull request by N0NB**
Tom, you were correct in your initial assessment that keypad() was not being called when switching from the cluster back to the mainscreen.  I believe the arrow keys issue is correct as it is working here.  I don't see anywhere else in the code where a similar issue exists, but more testing is probably warranted.

I've issued a merge request as I think we can try some wider testing now.

### CODE REVIEW

**Comment by N0NB** [comment]
Per Tom's suggestion, adding Alt-PageUp/PageDown for controlling Auto CQ delay.

**Comment by dl1jbe** [comment]
Just tested the code. Congratulations. The packet terminal problem got fixed.

But the added ALT-PgUp/Dwn does not work (for xfce and xterm at least). As it seems your definition of keycodes at the end of tlf_ncurses.h is wrong. 

ALT-pgUp is 548 and ALt-PgDwn ist 543 here. Can you please check where that values are coming from?

**Comment by dl1jbe** [comment]
Btw, it would be nice if you could have a look at the macro problem in issue #64 Nate. Thanks.

**Comment by N0NB** [comment]
* On 2016 23 Jan 04:25 -0600, Thomas Beierlein wrote:
> Just tested the code. Congratulations. The packet terminal problem got
> fixed.

I think I've found a memory leak that I will be posting to the list
later today.  Stay tuned.

> But the added ALT-PgUp/Dwn does not work (for xfce and xterm at
> least). As it seems your definition of keycodes at the end of
> tlf_ncurses.h is wrong.

Sigh.

> ALT-pgUp is 548 and ALt-PgDwn ist 543 here. Can you please check where
> that values are coming from?

My system reports:
Ordinal: 553            Name: kPRV3
Ordinal: 548            Name: kNXT3

For Alt-PgUp and Alt-PgDown, respectively.  AIUI, those values are
determined by the terminfo database entry for a particular terminal.

Can you run the new-onechar program I posted a couple of weeks ago and
see if it is getting the key names correct?  Are you using a different
keyboard/keyboard mapping than me (US 101/US QWERTY)?

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by dl1jbe** [comment]
Am Sat, 23 Jan 2016 05:13:02 -0800
schrieb Nate Bargmann <notifications@github.com>:

> * On 2016 23 Jan 04:25 -0600, Thomas Beierlein wrote:
> > Just tested the code. Congratulations. The packet terminal problem
> > got fixed.
> 
> I think I've found a memory leak that I will be posting to the list
> later today.  Stay tuned.
> 
Ok. 

> > But the added ALT-PgUp/Dwn does not work (for xfce and xterm at
> > least). As it seems your definition of keycodes at the end of
> > tlf_ncurses.h is wrong.
> 
> Sigh.
> 
> > ALT-pgUp is 548 and ALt-PgDwn ist 543 here. Can you please check
> > where that values are coming from?
> 
> My system reports:
> Ordinal: 553            Name: kPRV3
> Ordinal: 548            Name: kNXT3
> 
> For Alt-PgUp and Alt-PgDown, respectively.  AIUI, those values are
> determined by the terminfo database entry for a particular terminal.
> 
I am not sure if these extended combinations are handled in a standard
way. And I am not quite sure where the mapping from the escape sequence
in terminfo to the key-code number is done. Do you have a hint for me?

> Can you run the new-onechar program I posted a couple of weeks ago and
> see if it is getting the key names correct?  Are you using a different
> keyboard/keyboard mapping than me (US 101/US QWERTY)?
> 

Please see my mail regarding "Improved keyboard handling" on the
tlf-devel list from 5Jan16. There you can find the output of your
program for xfce terminal, xterm and rxvt on my keyboard.

I have here an european version (german) with 102 keys. But I do no
know if that makes a difference.

Tom


-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by N0NB** [comment]
* On 2016 23 Jan 08:26 -0600, Thomas Beierlein wrote:

> I am not sure if these extended combinations are handled in a standard
> way. And I am not quite sure where the mapping from the escape sequence
> in terminfo to the key-code number is done. Do you have a hint for me?

Right now, I am thinking that since the key values are defined in
terminfo and since the ncurses keyname() function reports the names and
since curses.h defines no key values above KEY_RESIZE, that if the value
is received greater than KEY_RESIZE, that keyname() be used to determine
which key was pressed.  This would take the Auto_CQ dealy keys out of
the switch statement, but that is probably a minor performance hit.

I can make up a patch and give it some testing.

> Please see my mail regarding "Improved keyboard handling" on the
> tlf-devel list from 5Jan16. There you can find the output of your
> program for xfce terminal, xterm and rxvt on my keyboard.
> 
> I have here an european version (german) with 102 keys. But I do no
> know if that makes a difference.

Thanks, I will recheck that mail.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by N0NB** [comment]
* On 2016 23 Jan 08:26 -0600, Thomas Beierlein wrote:
> Am Sat, 23 Jan 2016 05:13:02 -0800
> schrieb Nate Bargmann <notifications@github.com>:
> 
> > > ALT-pgUp is 548 and ALt-PgDwn ist 543 here. Can you please check
> > > where that values are coming from?
> > 
> > My system reports:
> > Ordinal: 553            Name: kPRV3
> > Ordinal: 548            Name: kNXT3
> > 
> > For Alt-PgUp and Alt-PgDown, respectively.  AIUI, those values are
> > determined by the terminfo database entry for a particular terminal.

> I am not sure if these extended combinations are handled in a standard
> way. And I am not quite sure where the mapping from the escape sequence
> in terminfo to the key-code number is done. Do you have a hint for me?
> 
> > Can you run the new-onechar program I posted a couple of weeks ago and
> > see if it is getting the key names correct?  Are you using a different
> > keyboard/keyboard mapping than me (US 101/US QWERTY)?
> > 
> 
> Please see my mail regarding "Improved keyboard handling" on the
> tlf-devel list from 5Jan16. There you can find the output of your
> program for xfce terminal, xterm and rxvt on my keyboard.

Here is what you reported then:

> Here just a test with your program for the PgUp and PgDn on three
> terminals:
>
>
>             xfce terminal   xterm       rxvt
> Ctrl-PgUp       --         550 kPRV5   530 kPRV5
> Ctrl-PgDn       --         545 kNXT5   528 kNXT5
> Alt-PgUp    548 kPRV3      548 kPRV5   338 KEY_NPAGE
> Alt-PgDn    543 kNXT3      543 kNXT5   339 KEY_PPAGE

It looks like rxvt will report PageUp and Page-Down instead of the Alt
combinations but will report the Ctrl combinations so my idea should be
workable.

73, Nate


-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by dl1jbe** [comment]
Am Sat, 23 Jan 2016 06:59:13 -0800
schrieb Nate Bargmann <notifications@github.com>:

> * On 2016 23 Jan 08:26 -0600, Thomas Beierlein wrote:
> > Am Sat, 23 Jan 2016 05:13:02 -0800
> > schrieb Nate Bargmann <notifications@github.com>:
> > 
> > > > ALT-pgUp is 548 and ALt-PgDwn ist 543 here. Can you please check
> > > > where that values are coming from?
> > > 
> > > My system reports:
> > > Ordinal: 553            Name: kPRV3
> > > Ordinal: 548            Name: kNXT3
> > > 
> > > For Alt-PgUp and Alt-PgDown, respectively.  AIUI, those values are
> > > determined by the terminfo database entry for a particular
> > > terminal.
> 
> > I am not sure if these extended combinations are handled in a
> > standard way. And I am not quite sure where the mapping from the
> > escape sequence in terminfo to the key-code number is done. Do you
> > have a hint for me?
> > 
> > > Can you run the new-onechar program I posted a couple of weeks
> > > ago and see if it is getting the key names correct?  Are you
> > > using a different keyboard/keyboard mapping than me (US 101/US
> > > QWERTY)?
> > > 
> > 
> > Please see my mail regarding "Improved keyboard handling" on the
> > tlf-devel list from 5Jan16. There you can find the output of your
> > program for xfce terminal, xterm and rxvt on my keyboard.
> 
> Here is what you reported then:
> 
> > Here just a test with your program for the PgUp and PgDn on three
> > terminals:
> >
> >
> >             xfce terminal   xterm       rxvt
> > Ctrl-PgUp       --         550 kPRV5   530 kPRV5
> > Ctrl-PgDn       --         545 kNXT5   528 kNXT5
> > Alt-PgUp    548 kPRV3      548 kPRV5   338 KEY_NPAGE
> > Alt-PgDn    543 kNXT3      543 kNXT5   339 KEY_PPAGE

There is an error of mine above. It should be kPRV3 and KNXT3 in xterm
column last two lines.
> 
> It looks like rxvt will report PageUp and Page-Down instead of the Alt
> combinations but will report the Ctrl combinations so my idea should
> be workable.
> 
I am not quite sure what idea you are talking about.
Let us leave rxvt beside. But for xfce and xterm we have a difference
between the key handling hre and at your side.

                    mine   yours
Alt-PgUp kPRV3       548    553
Alt-PgDn kNXT3       543    548

Maybe a reason is also that these combinations are not defined in
the xterm terminfo here.

Tom


-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by N0NB** [comment]
I pushed a patch out that should give my idea clarity.  :-)

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by dl1jbe** [comment]
Am Sat, 23 Jan 2016 10:00:25 -0800
schrieb Nate Bargmann <notifications@github.com>:

> I pushed a patch out that should give my idea clarity.  :-)
> 
> 73, Nate
> 

Ok, I see what you had in mind. The only donwside is the keyname()
lookup and the string compare for each key press.

I was in meantime on a similar track: Look if we can ask ncurses about
the actual key code for kNXT3/kPRV3 during initialisation and use that
value afterwards.

ATM the only solution I found is to get the ESC sequence with tigetstr
and afterwards look up the code from the ESC-string. 

 char *name = tigetstr("kNXT3");
 int kNXT3_code = key_defined(name);

The sequence needs some checks if the key is not found but I hope it
shows the idea. 

I have send a question about a simpler way to do the above to the
ncurses mailing list. Let us see if we get some better ideas from there.

Tom.

-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Comment by N0NB** [comment]
* On 2016 24 Jan 03:32 -0600, Thomas Beierlein wrote:
> Ok, I see what you had in mind. The only donwside is the keyname()
> lookup and the string compare for each key press.

Indeed.

> I was in meantime on a similar track: Look if we can ask ncurses about
> the actual key code for kNXT3/kPRV3 during initialisation and use that
> value afterwards.
> 
> ATM the only solution I found is to get the ESC sequence with tigetstr
> and afterwards look up the code from the ESC-string. 
> 
>  char *name = tigetstr("kNXT3");
>  int kNXT3_code = key_defined(name);
> 
> The sequence needs some checks if the key is not found but I hope it
> shows the idea.

Probably a much better idea.  I doubt there is any method more simple.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by dl1jbe** [comment]
As we got no negative feedback from the test release I merged the code into the master branch.
Thanks again Nate for the heavy bunch of work you provided here.

**Comment by N0NB** [comment]
* On 2016 12 Feb 13:24 -0600, Thomas Beierlein wrote:
> As we got no negative feedback from the test release I merged the code
> into the master branch.  Thanks again Nate for the heavy bunch of work
> you provided here.

You're quite welcome, Tom.

I benefited in several ways by doing this.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Pull request merged**
